
src-y += reg.cppm heap.cppm exception.cppm fmt.cppm time.cppm hexdump.cppm utils.cppm timer.cppm
src-y += backtrace.cppm heap-malloc.cpp elist.cppm equeue.cppm async.cppm
src-y += allocator/
src-y += lock/
src-y += timestamp/

src-$(CONFIG_LIB_GPIO) += gpio.cppm
src-$(CONFIG_LIB_I2C) += i2c.cppm
src-y += servo.cppm
