LOCAL_DIR = $(GET_LOCAL_DIR)

srcs += $(LOCAL_DIR)/test.cpp
srcs += $(LOCAL_DIR)/vector.cpp
srcs += $(LOCAL_DIR)/tuple.cpp

GLOBAL_CFLAGS += -I$(LOCAL_DIR)/include
GLOBAL_LDFLAGS += -T$(LOCAL_DIR)/test.lds
