LOCAL_DIR = $(GET_LOCAL_DIR)

mod_srcs += $(LOCAL_DIR)/string.cppm
mod_srcs += $(LOCAL_DIR)/type_traits.cppm
mod_srcs += $(LOCAL_DIR)/concepts.cppm
mod_srcs += $(LOCAL_DIR)/initializer_list.cppm
mod_srcs += $(LOCAL_DIR)/vector.cppm
mod_srcs += $(LOCAL_DIR)/tuple.cppm
mod_srcs += $(LOCAL_DIR)/memory.cppm

srcs += $(LOCAL_DIR)/new.cpp

GLOBAL_CFLAGS += -I$(LOCAL_DIR)/include
