LOCAL_DIR = $(GET_LOCAL_DIR)

mod_srcs += $(LOCAL_DIR)/string.cppm
mod_srcs += $(LOCAL_DIR)/type_traits.cppm
mod_srcs += $(LOCAL_DIR)/concepts.cppm

srcs += $(LOCAL_DIR)/new.cpp

GLOBAL_CFLAGS += -I$(LOCAL_DIR)/include
