
GLOBAL_CPPFLAGS += -DCONFIG_SOC_RP2040

src-y += bs2_default_padded_checksummed.S
src-y += start.S

src-y += rp2040.cppm
src-y += cpu.cppm
src-y += address_map.cppm
src-y += lock.cppm
src-y += gpio.cppm
src-y += timer.cppm
src-y += timestamp.cppm
src-y += pwm.cppm
src-y += i2c.cppm
src-y += spi.cppm
src-y += mailbox.cppm
src-y += multicore.cppm
src-y += hwspinlock.cppm
src-y += thread.cppm
src-y += bootrom.cppm
src-y += reset.cppm
src-y += rtc.cppm
