name: SC CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Setup dependencies
      run: |
        sudo apt-get install -y llvm-10 clang-10 lld-10 qemu-system-arm
        sudo update-alternatives \
            --install /usr/bin/llvm-objcopy llvm-objcopy /usr/bin/llvm-objcopy-10 100
        sudo update-alternatives \
            --install /usr/bin/ld.lld ld.lld /usr/bin/ld.lld-10 100

    - name: make
      run: make V=1

    - name: Run all test
      run: make clean qemu RUN_ALL_TESTS=1 TARGET=qemu-aarch64
